name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Cache PDM
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Install dependencies
        run: |
          pdm install -G dev

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: |
          pdm run pytest -q

